// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousPlaceGear extends CommandGroup
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutonomousPlaceGear(String GearLocation) {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		// Add Commands here:
		// e.g. addSequential(new Command1());
		// addSequential(new Command2());
		// these will run in order.

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		// addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

		if (GearLocation == "Left")
		{
			addSequential(new ChassisDriveDistance(80.0, -0.8, false));
			addSequential(new ChassisTurnAngle(65.0, 0.0, false));
		} 
		else if (GearLocation == "Center" || GearLocation == "Center No Run")
		{
			addSequential(new ChassisDriveDistance(30.0, -0.8, false));  // 40 
		} 
		else if (GearLocation == "Right")
		{
			addSequential(new ChassisDriveDistance(80.0, -0.8, false));
			addSequential(new ChassisTurnAngle(-65.0, 0.0, false));
		}

		// Deliver the gear
		addSequential(new AutoDeliverGear());
		
		if (GearLocation == "Center")
		{
			// on center run away to cross baseline
			addSequential(new ChassisDriveDistance(20.0, 0.8, false));
			addSequential(new ChassisTurnAngle(-60.0, 0.0, false));
			addSequential(new ChassisDriveDistance(60.0, -0.8, false));
		}
		else if (GearLocation == "Center No Run")
		{
			// straight forward to cross baseline
			//addSequential(new ChassisDriveDistance(20.0, -0.2, false));
		}
	}
}
