// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;

/**
 *
 */
public class AutonomousGearPlaceCenter extends CommandGroup
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
    public AutonomousGearPlaceCenter() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		// Add Commands here:
		// e.g. addSequential(new Command1());
		// addSequential(new Command2());
		// these will run in order.

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		// addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS
		
    	// Drive up to lift
		addSequential(new ChassisDriveDistance(50.0, -0.4, false));
		addSequential(new GearRotateUp());
		addSequential(new Delay(1.0));
		
		// Move gear onto lift
		addSequential(new ChassisDriveRange(10.0, -0.3, false));
		addSequential(new Delay(1.0));
		
		// Drop Gear off 
		addSequential(new GearRelease());
		addSequential(new Delay(1.0));
		addSequential(new GearRotateDown());
		
		// Drive back
		addSequential(new ChassisDriveDistance(48.0, 0.5, false));
		
		// Run away to cross baseline
		addSequential(new ChassisTurnAngle(-75.0, 0.0, false));
		addSequential(new ChassisDriveDistance(60.0, -0.8, false));
		addSequential(new ChassisTurnAngle(60.0, 0.0, false));
		addSequential(new ChassisDriveDistance(60.0, -0.8, false));
	}
}
