// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.commands;

import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc3824.Competition2017.Robot;

/**
 *
 */
public class ChassisDriveRange extends Command
{	
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
	private double	m_Distance;
	private double	m_Power;
	private boolean	m_HighGear;

	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
	public ChassisDriveRange(double Distance, double Power, boolean HighGear)
	{
		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		m_Distance = Distance;
		m_Power = Power;
		m_HighGear = HighGear;

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.chassis);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	}

	// Called just before this Command runs the first time
	protected void initialize()
	{
		// Determine the PID direction and power
		boolean driveForward = Robot.chassis.getUltrasonicDistance() - m_Distance > 0.0;

		// If driving backwards, then reverse the "forward" boolean
		if (m_Power < 0)
			driveForward = !driveForward;
			
		// Set the PID up for driving straight
		Robot.chassis.driveStraightPID(0.4 * (driveForward ? 1.0 : -1.0), m_HighGear);
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute()
	{
		// make sure we're driving in the correct direction
		double distanceDelta = Robot.chassis.getUltrasonicDistance() - m_Distance;
		boolean driveForward = distanceDelta > 0.0;
		
		// If driving backwards, then reverse the "forward" boolean
		if (m_Power < 0)
			driveForward = !driveForward;

		// Slow down when close to stop point
		if (Math.abs(distanceDelta) < 24.0)
		{
			Robot.chassis.updateMagnitude(0.3 * (driveForward ? 1.0 : -1.0));
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished()
	{
		// Determine if the robot has reached the desired distance
		return Math.abs(m_Distance - Robot.chassis.getUltrasonicDistance()) < 2.0;
	}

	// Called once after isFinished returns true
	protected void end()
	{
		// Stop the chassis controllers and reset the encoders
		Robot.chassis.resetChassisPIDcontrollersAndEncoders();
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted()
	{
		end();
	}
}
