// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.commands;

import edu.wpi.first.wpilibj.command.CommandGroup;
import org.usfirst.frc3824.Competition2017.subsystems.*;

/**
 *
 */
public class SimpleDeliverGear extends CommandGroup
{

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
	public SimpleDeliverGear()
	{

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PARAMETERS
		// Add Commands here:
		// e.g. addSequential(new Command1());
		// addSequential(new Command2());
		// these will run in order.

		// To run multiple commands at the same time,
		// use addParallel()
		// e.g. addParallel(new Command1());
		// addSequential(new Command2());
		// Command1 and Command2 will run in parallel.

		// A command group will require all of the subsystems that each member
		// would require.
		// e.g. if Command1 requires chassis, and Command2 requires arm,
		// a CommandGroup containing them would require both the chassis and the
		// arm.
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

		// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=COMMAND_DECLARATIONS

		// Rotate up
		addSequential(new GearRotateUp());
		addSequential(new Delay(0.5));

		// Drive up to lift to place gear
		addSequential(new ChassisDriveRange(5.0, -0.3, false), 2.0);

		// Release the gear
		addSequential(new GearRelease(), 1.0);
		// addSequential(new Delay(0.25)); // 0.75

		// Back up to allow the gear to rotate down
		addSequential(new ChassisDriveDistance(1.0, 0.2, false), 2.0);
		addSequential(new Delay(0.25));

		// Rotate the gear handler down
		addSequential(new GearRotateDown(), 1.0);
		addSequential(new Delay(0.5));
		
		// Back away from lift
		addSequential(new ChassisDriveDistance(30.0, 0.5, false), 2.0);
	}
}
