// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.subsystems;

import org.usfirst.frc3824.Competition2017.Constants;
import org.usfirst.frc3824.Competition2017.RobotMap;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Solenoid;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Gear extends Subsystem
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final Solenoid pusher = RobotMap.gearPusher;
    private final CANTalon sucker = RobotMap.gearSucker;
    private final CANTalon rotator = RobotMap.gearRotator;
    private final Solenoid locker = RobotMap.gearLocker;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    public Gear()
    {
    	// Setup gear manipulation rotator feedback and output
    	rotator.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Absolute);    	
    	rotator.reverseSensor(false);   	
    	rotator.configNominalOutputVoltage(0.0f,  0.0f);
    	rotator.configPeakOutputVoltage(12.0f,  -12.0f);
    	rotator.reverseOutput(false);
    	rotator.setProfile(0);
    	rotator.configEncoderCodesPerRev(4096);
    	rotator.setP(Constants.ROTATOR_P);
    	rotator.setI(Constants.ROTATOR_I);
    	rotator.setD(Constants.ROTATOR_D);
    	rotator.setF(Constants.ROTATOR_F);
    	rotator.changeControlMode(CANTalon.TalonControlMode.Position);
    	
    	// Setup gear manipulation intake feedback and output
    	sucker.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
    	sucker.reverseSensor(false);   	
    	sucker.configNominalOutputVoltage(0.0f,  0.0f);
    	sucker.configPeakOutputVoltage(12.0f,  -12.0f);
    	sucker.reverseOutput(false);
    	sucker.setProfile(0);
    	sucker.configEncoderCodesPerRev(4096);
    	sucker.setP(Constants.SUCKER_P);
    	sucker.setI(Constants.SUCKER_I);
    	sucker.setD(Constants.SUCKER_D);
    	sucker.setF(Constants.SUCKER_F);
    	sucker.changeControlMode(CANTalon.TalonControlMode.Speed);
    	
    	resetAndEnableGear();
    }
    
	// Put methods for controlling this subsystem
	// here. Call these from Commands.
    
    /**
	 * Method to reset and enable the encoder input for the gear rotator
	 */
    public void resetAndEnableGear()
    {
    	rotator.reset();
    	rotator.enable();
    	sucker.reset();
    	sucker.enable();
    }
    
    /**
	 * Method to update the encoder PID setpoint for the gear rotator
	 */
    public void updateRotatorSetpoint(int encoderValue)
    {
    	rotator.setSetpoint(encoderValue);
    }
    
    public double getRotatorEncoderValue()
    {
    	return rotator.getEncPosition();
    }
    
	/**
	 * Method to set the intake speed
	 */
	public void setIntake(double speed)
	{
		sucker.setSetpoint(speed);
	}
	
	/**
	 * Method to get the intake speed
	 */
	public double getIntakeSpeed()
	{
		return sucker.getSpeed();
	}
    
	/**
	 * Method to set the position of the gear rotator
	 */
	public void setRotator(String pos)
	{	
		if (pos.equals("Up"))
		{
			updateRotatorSetpoint(Constants.UP_ROTATOR_POS);
		} else if (pos.equals("Down"))
		{
			updateRotatorSetpoint(Constants.DOWN_ROTATOR_POS);
		} else
		{
			updateRotatorSetpoint(Constants.PLACE_ROTATOR_POS);
		}
	}
	
	/**
	 * Method to set the gear pusher piston in or out
	 *    true  - out
	 *    false - in
	 */
	public void setPush(boolean in)
	{
		pusher.set(in);
	}

	/**
	 * Method to get the current position of the gear pusher
	 */
	public boolean getPush()
	{
		return pusher.get();
	}
	
	/**
	 * Method to set the gear locker piston in or out
	 *    true  - out
	 *    false - in
	 */
	public void setLock(boolean in)
	{
		locker.set(in);
	}

	/**
	 * Method to get the current position of the gear locker
	 */
	public boolean getLock()
	{
		return locker.get();
	}
	
	public void initDefaultCommand()
	{
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

		// Set the default command for a subsystem here.
		// setDefaultCommand(new MySpecialCommand());
	}	
}
