// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3824.Competition2017.subsystems;

import org.usfirst.frc3824.Competition2017.RobotMap;
import org.usfirst.frc3824.Competition2017.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 *
 */
public class Shooter extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon shooter = RobotMap.shooterShooter;
    private final CANTalon feeder = RobotMap.shooterFeeder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public Shooter()
	{
		shooter.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
		shooter.reverseSensor(true);

		/* set the peak and nominal outputs, 12V means full */
		shooter.configNominalOutputVoltage(+0.0f, -0.0f);
		shooter.configPeakOutputVoltage(+12.0f, -12.0f);

		/* set closed loop gains in slot0 */
		SmartDashboard.putNumber("Shooter P", 50.0);
		SmartDashboard.putNumber("Shooter I", 0.4);
		SmartDashboard.putNumber("Shooter D", 0.0);
		SmartDashboard.putNumber("Shooter F", 0.0);
		SmartDashboard.putNumber("Shooter RPM Setpoint", 4500);

		// Set the profile for the PID parameters
		shooter.setProfile(0);
		shooter.configEncoderCodesPerRev(4096);

		// Use the PID values from the smartdashboard, which were just set
		shooter.setP(SmartDashboard.getNumber("Shooter P", 50.0)/1000);
		shooter.setI(SmartDashboard.getNumber("Shooter I", 0.4)/1000);
		shooter.setD(SmartDashboard.getNumber("Shooter D", 0.0)/1000);
		shooter.setF(SmartDashboard.getNumber("Shooter F", 0.0)/1000);

		
		// Feeder
		
		feeder.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
		feeder.reverseSensor(false);

		/* set the peak and nominal outputs, 12V means full */
		feeder.configNominalOutputVoltage(+0.0f, -0.0f);
		feeder.configPeakOutputVoltage(+12.0f, -12.0f);

		/* set closed loop gains in slot0 */
		SmartDashboard.putNumber("Feeder P", 50.0);
		SmartDashboard.putNumber("Feeder I", 0.4);
		SmartDashboard.putNumber("Feeder D", 0.0);
		SmartDashboard.putNumber("Feeder F", 0.0);
		SmartDashboard.putNumber("Feeder RPM Setpoint", 500);

		// Set the profile for the PID parameters
		feeder.setProfile(0);
		feeder.configEncoderCodesPerRev(4096);
		feeder.reverseSensor(true);

		// Use the PID values from the smartdashboard, which were just set
		feeder.setP(SmartDashboard.getNumber("Feeder P", 50.0)/1000);
		feeder.setI(SmartDashboard.getNumber("Feeder I", 0.4)/1000);
		feeder.setD(SmartDashboard.getNumber("Feeder D", 0.0)/1000);
		feeder.setF(SmartDashboard.getNumber("Feeder F", 0.0)/1000);

	}
	
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
    }
    
	public void setShooterRPM(double RPM)
	{
		// Set the Talon in PID speed mode
		shooter.changeControlMode(CANTalon.TalonControlMode.Speed);

		// Set the desired speed
		shooter.set(RPM);
	}

	public void setFeederRPM(double RPM)
	{
		// Set the Talon in PID speed mode
		feeder.changeControlMode(CANTalon.TalonControlMode.Speed);

		// Set the desired speed
		feeder.set(RPM);
	}
	
	public void enablePIDs()
	{
		shooter.enable();
		feeder.enable();
	}
	
	public void disablePIDs()
	{
		shooter.disable();
		feeder.disable();
	}

	public void setShooterPID_Parameters(double F, double P, double I, double D)
	{
		// Read the F, P, I and D parameters from the smartdashboard
		shooter.setF(F);
		shooter.setP(P);
		shooter.setI(I);
		shooter.setD(D);
	}
	
	public void setShooterPID_ParametersFromSmartdashboard()
	{
		// Read the F, P, I and D parameters from the smartdashboard
		// divide everthing by 1000 so smart dashboard numbers are not really small
		shooter.setF(SmartDashboard.getNumber("Shooter F", 0.0)/1000);
		shooter.setP(SmartDashboard.getNumber("Shooter P", 0.0)/1000);
		shooter.setI(SmartDashboard.getNumber("Shooter I", 0.0)/1000);
		shooter.setD(SmartDashboard.getNumber("Shooter D", 0.0)/1000);
	}
	
	public void setShooterRPM_FromSmartdashboard()
	{
		setShooterRPM(SmartDashboard.getNumber("Shooter RPM Setpoint", 4500));
	}


	public void setFeederPID_Parameters(double F, double P, double I, double D)
	{
		// Read the F, P, I and D parameters from the smartdashboard
		feeder.setF(F);
		feeder.setP(P);
		feeder.setI(I);
		feeder.setD(D);
	}
	
	public void setFeederPID_ParametersFromSmartdashboard()
	{
		// Read the F, P, I and D parameters from the smartdashboard
		// divide everthing by 1000 so smart dashboard numbers are not really small
		feeder.setF(SmartDashboard.getNumber("Feeder F", 0.0)/1000);
		feeder.setP(SmartDashboard.getNumber("Feeder P", 0.0)/1000);
		feeder.setI(SmartDashboard.getNumber("Feeder I", 0.0)/1000);
		feeder.setD(SmartDashboard.getNumber("Feeder D", 0.0)/1000);
	}
	
	public void setFeederRPM_FromSmartdashboard()
	{
		setFeederRPM(SmartDashboard.getNumber("Feeder RPM Setpoint", 500));
	}
	
}

