// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc3824.Competition2017.subsystems;

import org.usfirst.frc3824.Competition2017.Constants;
import org.usfirst.frc3824.Competition2017.RobotMap;
import org.usfirst.frc3824.Competition2017.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Shooter extends Subsystem
{
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final CANTalon shooterA = RobotMap.shooterShooterA;
    private final CANTalon shooterB = RobotMap.shooterShooterB;
    private final CANTalon feeder = RobotMap.shooterFeeder;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

	public Shooter()
	{
		// Set closed loop gains in slot0
		SmartDashboard.putNumber("Shooter P", Constants.SHOOTER_P * 1000.0);
		SmartDashboard.putNumber("Shooter I", Constants.SHOOTER_I * 1000.0);
		SmartDashboard.putNumber("Shooter D", Constants.SHOOTER_D * 1000.0);
		SmartDashboard.putNumber("Shooter F", Constants.SHOOTER_F * 1000.0);
		SmartDashboard.putNumber("Shooter RPM Setpoint", 4500);
		
		// Set closed loop gains in slot0
		SmartDashboard.putNumber("Feeder P", Constants.FEEDER_P * 1000.0);
		SmartDashboard.putNumber("Feeder I", Constants.FEEDER_I * 1000.0);
		SmartDashboard.putNumber("Feeder D", Constants.FEEDER_D * 1000.0);
		SmartDashboard.putNumber("Feeder F", Constants.FEEDER_F * 1000.0);
		SmartDashboard.putNumber("Feeder RPM Setpoint", 500);
		
		//********************************************************************
		// Configure the Shooter A Talon SRX
		//********************************************************************

		shooterA.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
		shooterA.reverseSensor(true);

		// Set the peak and nominal outputs, 12V means full
		shooterA.configNominalOutputVoltage(0.0f, 0.0f);
		shooterA.configPeakOutputVoltage(12.0f, -12.0f);
		shooterA.reverseOutput(false);

		// Set the profile for the PID parameters
		shooterA.setProfile(0);
		shooterA.configEncoderCodesPerRev(4096);
		
		// Use the PID values 
		shooterA.setP(Constants.SHOOTER_P);
		shooterA.setI(Constants.SHOOTER_I);
		shooterA.setD(Constants.SHOOTER_D);
		shooterA.setF(Constants.SHOOTER_F);

		//********************************************************************
		// Configure the Shooter B Talon SRX
		//********************************************************************

		shooterB.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
		shooterB.reverseSensor(true);

		// Set the peak and nominal outputs, 12V means full
		shooterB.configNominalOutputVoltage(0.0f, 0.0f);
		shooterB.configPeakOutputVoltage(12.0f, -12.0f);
		shooterB.reverseOutput(false);
		
		// Set the profile for the PID parameters
		shooterB.setProfile(0);
		shooterB.configEncoderCodesPerRev(4096);
		
		// Use the PID values 
		shooterB.setP(Constants.SHOOTER_P);
		shooterB.setI(Constants.SHOOTER_I);
		shooterB.setD(Constants.SHOOTER_D);
		shooterB.setF(Constants.SHOOTER_F);
		
		//********************************************************************
		// Configure the Feeder Talon SRX
		//********************************************************************
		feeder.setFeedbackDevice(CANTalon.FeedbackDevice.CtreMagEncoder_Relative);
		feeder.reverseSensor(true);

		// Set the peak and nominal outputs, 12V means full
		feeder.configNominalOutputVoltage(0.0f, 0.0f);
		feeder.configPeakOutputVoltage(12.0f, -12.0f);
		feeder.reverseOutput(false);

		// Set the profile for the PID parameters
		feeder.setProfile(0);
		feeder.configEncoderCodesPerRev(4096);

		// Use the PID values from the SmartDashboard, which were just set
		feeder.setP(Constants.FEEDER_P);
		feeder.setI(Constants.FEEDER_I);
		feeder.setD(Constants.FEEDER_D);
		feeder.setF(Constants.FEEDER_F);
	}

	public void initDefaultCommand()
	{
		// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	}

	/**
	 * Method to set the Shooter wheel speed
	 */
	public void setShooterSpeed(double speed)
	{
		// Set the Talon in PID speed mode
		shooterA.changeControlMode(CANTalon.TalonControlMode.Speed);
		shooterB.changeControlMode(CANTalon.TalonControlMode.Speed);

		// Set the desired speed
		shooterA.set(speed);
		shooterB.set(speed);
	}

	/**
	 * Method to set the Feeder wheel RMP
	 */
	public void setFeederSpeed(double speed)
	{
		// Set the Talon in PID speed mode
		feeder.changeControlMode(CANTalon.TalonControlMode.Speed);

		// Set the desired speed
		feeder.set(speed);
	}

	/**
	 * Method to enable the shooter PID controller
	 */
	public void enableShooterPIDs()
	{
		// Enable both shooter PID controllers
		shooterA.enable();
		shooterB.enable();
	}
	
	/**
	 * Method to enable the feeder PID controller
	 */
	public void enableFeederPID()
	{
		// Enable the feeder PID controller
		feeder.enable();
	}

	/**
	 * Method to disable the Shooter PID controllers
	 */
	public void disableShooterPIDs()
	{
		// Disable both shooter PID controllers
		shooterA.disable();
		shooterB.disable();
	}
	
	/**
	 * Method to disable the Feeder PID controller
	 */
	public void disableFeederPID()
	{
		// Disable the feeder PID controller
		feeder.disable();
	}

	/**
	 * Method to set the Shooter PID parameters
	 */
	public void setShooterPID_Parameters(double F, double P, double I, double D)
	{
		// Set the F, P, I and D parameters for shooter motor A PID controller
		shooterA.setF(F);
		shooterA.setP(P);
		shooterA.setI(I);
		shooterA.setD(D);
		
		// Set the F, P, I and D parameters for shooter motor B PID controller
		shooterB.setF(F);
		shooterB.setP(P);
		shooterB.setI(I);
		shooterB.setD(D);
	}

	/**
	 * Method to set the Feeder PID parameters
	 */
	public void setFeederPID_Parameters(double F, double P, double I, double D)
	{
		// Set the F, P, I and D parameters for the feeder PID controller
		feeder.setF(F);
		feeder.setP(P);
		feeder.setI(I);
		feeder.setD(D);
	}
	
	/**
	 * Method to read the shooter PID parameters from the SmartDashboard
	 */
	public void setShooterPID_ParametersFromSmartdashboard()
	{
		// Read the F, P, I and D parameters for shooter motor A from the SmartDashboard
		// divide everything by 1000 so SmartDashboard numbers are not really small
		shooterA.setF(SmartDashboard.getNumber("Shooter F", 0.0) / 1000);
		shooterA.setP(SmartDashboard.getNumber("Shooter P", 0.0) / 1000);
		shooterA.setI(SmartDashboard.getNumber("Shooter I", 0.0) / 1000);
		shooterA.setD(SmartDashboard.getNumber("Shooter D", 0.0) / 1000);
		
		// Read the F, P, I and D parameters for shooter motor B from the SmartDashboard
		shooterB.setF(SmartDashboard.getNumber("Shooter F", 0.0) / 1000);
		shooterB.setP(SmartDashboard.getNumber("Shooter P", 0.0) / 1000);
		shooterB.setI(SmartDashboard.getNumber("Shooter I", 0.0) / 1000);
		shooterB.setD(SmartDashboard.getNumber("Shooter D", 0.0) / 1000);
	}

	/**
	 * Method to set the Feeder PID parameters from the SmartDashboard
	 */
	public void setFeederPID_ParametersFromSmartdashboard()
	{
		// Read the F, P, I and D parameters for the feeder motor from the SmartDashboard
		// divide everything by 1000 so SmartDashboard numbers are not really small
		feeder.setF(SmartDashboard.getNumber("Feeder F", 0.0) / 1000);
		feeder.setP(SmartDashboard.getNumber("Feeder P", 0.0) / 1000);
		feeder.setI(SmartDashboard.getNumber("Feeder I", 0.0) / 1000);
		feeder.setD(SmartDashboard.getNumber("Feeder D", 0.0) / 1000);
	}	
	
	/**
	 * Method to set the Shooter speed from the SmartDashboard
	 */
	public void setShooterSpeedFromSmartdashboard()
	{
		// Set the Shooter speed from the SmartDashboard
		setShooterSpeed(SmartDashboard.getNumber("Shooter RPM Setpoint", 4500));
	}

	/**
	 * Method to set the Feeder speed from the SmartDashboard
	 */
	public void setFeederSpeedFromSmartdashboard()
	{
		// Set the Feeder speed from the SmartDashboard
		setFeederSpeed(SmartDashboard.getNumber("Feeder RPM Setpoint", 500));
	}
	
	/**
	 * Method to set the Shooter Power in volts
	 */
	public void setShooterPower(double power)
	{
		// Set the Talon in PID voltage mode
		shooterA.changeControlMode(CANTalon.TalonControlMode.Voltage);
		shooterB.changeControlMode(CANTalon.TalonControlMode.Voltage);
		
		// Set the shooter outputs
		shooterA.set(power);
		shooterB.set(power);
	}
	
	/**
	 * Method to set the Feeder Power in volts
	 */
	public void setFeederPower(double power)
	{
		// Set the Talon in PID voltage mode
		feeder.changeControlMode(CANTalon.TalonControlMode.Voltage);
		feeder.set(power);
	}
	
	/**
	 * Method to return the Shooter speed
	 */
	public double getShooterSpeed()
	{
		// Assume shooter A and shooter B are set to the same speed
		return shooterA.getSpeed();
	}
	
	/**
	 * Method to return the Feeder speed
	 */
	public double getFeederSpeed()
	{
		// Return the feeder speed
		return feeder.getSpeed();
	}
}
